//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomaciZadatakMVC.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [Display(Name = "Id")]
        public int TaskId { get; set; }
        public string Status { get; set; }
        public string Progress { get; set; }
        public string Assignee { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Description { get; set; }

        [Display(Name = "Project Id")]
        public int ProjectId { get; set; }

        [Display(Name = "User Id")]
        public int UserId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
